version: '2'

networks:
  app-tier:
    driver: bridge

services:
  postgresql:
    environment:
      - POSTGRESQL_PASSWORD=ROOTPASSWD
    image: 'bitnami/postgresql:latest'
    networks:
      - app-tier
  myapp:
    image: 'python:latest'
    networks:
      - app-tier
