version: '2'

volumes:
  posdata:

networks:
  app-tier:
    driver: bridge

services:
  postgresql:
    environment:
      - POSTGRESQL_PASSWORD=${ROOTPASSWD}
    image: 'bitnami/postgresql:latest'
    volumes:
      - posdata:/bitnami/postgresql:rw
    networks:
      - app-tier
    expose:
      - "5432"
  myapp:
    image: 'python:latest'
    build:
      context: ./pythonapp
    networks:
      - app-tier
  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGEMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGPASSWD}
    image: 'dpage/pgadmin4'
    networks:
      - app-tier
    ports:
      - 80:80