version: '2'

networks:
  app-tier:
    driver: bridge

services:
  postgresql:
    environment:
      - POSTGRESQL_PASSWORD=${ROOTPASSWD}
    image: 'bitnami/postgresql:latest'
    networks:
      - app-tier
    expose:
      - "5432/TCP"
  myapp:
    image: 'python:latest'
    networks:
      - app-tier
  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGEMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGPASSWD}
    image: 'dpage/pgadmin4'
    networks:
      - app-tier
    ports:
      - 80:80